platform :ios, '10.0'
use_frameworks!
inhibit_all_warnings!

pod 'SwiftLint'
pod 'SwiftGen'


def app_pods
  pod 'SnapKit'
  pod 'Alamofire'
  pod 'R.swift'
  pod 'RxAlamofire' 
  pod 'RxCocoa'
  pod 'RxSwift'
end

def test_pods
  pod 'Quick'
  pod 'Nimble'
end

target 'MyProject' do
  app_pods
  end

  target 'MyProjectTests' do
    inherit! :search_paths
    test_pods
    # Pods for testing
  end

  target 'MyProjectUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
