platform :ios, '10.0'
use_frameworks!
inhibit_all_warnings!

def app_pods
  pod 'SnapKit'
  pod 'Alamofire'
  pod 'R.swift'
  pod 'RxAlamofire' 
  pod 'RxCocoa'
  pod 'RxSwift'
  pod 'SwiftLint'
  pod 'SwiftGen'
  pod 'FLEX', '~> 3.0', :configurations => ['Debug']


def test_pods
  pod 'Quick'
  pod 'Nimble'
end

target 'MyProject' do
  app_pods
end
  target 'MyProjectTests' do
    inherit! :search_paths
    test_pods
    # Pods for testing
  end

  target 'MyProjectUITests' do
    inherit! :search_paths
    # Pods for testing
  end
